all:
  children:
    clickhouse:
      hosts:
        clickhouse-01:
          ansible_host: 89.169.154.4
          ansible_user: alexey
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519

    lighthouse:
      hosts:
        lighthouse-01:
          ansible_host: 89.169.153.110
          ansible_user: alexey
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519

    vector:
      hosts:
        vector-01:
          ansible_host: 89.169.129.124
          ansible_user: alexey
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
