
#cloud-config
users:
  - name: alexey
    shell: /bin/bash
    groups: docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMqSVXDvPdBOlA2bdW7MHauhCEoxkRZmyx5FuH/s70XO tatarincev0810@gmail.com

#cloud-config
package_update: true
runcmd:
  - apt-get install -y apt-transport-https ca-certificates dirmngr
  - apt-key adv --keyserver keyserver.ubuntu.com --recv E0C56BD4
  - echo "deb https://packages.clickhouse.com/deb stable main" > /etc/apt/sources.list.d/clickhouse.list
  - apt-get update
  - apt-get install -y clickhouse-server clickhouse-client
  - systemctl enable clickhouse-server
  - systemctl start clickhouse-server
